// 오늘의 영어 숙어 데이터 & 유틸
const IDIOMS = [
  { en: "Break a leg", kr: "행운을 빌다", ex: "Break a leg on your presentation today!" },
  { en: "Hit the books", kr: "공부하다", ex: "I have a test tomorrow, so I need to hit the books." },
  { en: "Bite the bullet", kr: "이를 악물고 하다", ex: "Just bite the bullet and finish the assignment." },
  { en: "Under the weather", kr: "몸이 좋지 않다", ex: "I'm feeling a bit under the weather today." },
  { en: "Burn the midnight oil", kr: "밤새워 공부(일)하다", ex: "She burned the midnight oil to finish her report." },
  { en: "A piece of cake", kr: "식은 죽 먹기, 매우 쉬움", ex: "The exam was a piece of cake!" },
  { en: "Hit the nail on the head", kr: "핵심을 정확히 짚다", ex: "You hit the nail on the head with that analysis." },
  { en: "Let the cat out of the bag", kr: "비밀을 누설하다", ex: "Don't let the cat out of the bag about the surprise party." },
  { en: "Beat around the bush", kr: "핵심을 피하고 빙빙 돌리다", ex: "Stop beating around the bush and tell me the truth." },
  { en: "Bite off more than you can chew", kr: "감당 못 할 일을 맡다", ex: "Taking five courses was biting off more than I could chew." },
  { en: "Once in a blue moon", kr: "아주 드물게", ex: "He only calls me once in a blue moon." },
  { en: "Cost an arm and a leg", kr: "엄청나게 비싸다", ex: "That new phone costs an arm and a leg." },
  { en: "Spill the beans", kr: "비밀을 누설하다", ex: "Who spilled the beans about the surprise?" },
  { en: "On the fence", kr: "결정을 못 내리고 있다", ex: "I'm on the fence about which major to choose." },
  { en: "The ball is in your court", kr: "이제 네가 결정할 차례야", ex: "I've given you all the info. The ball is in your court." },
  { en: "Kill two birds with one stone", kr: "일석이조", ex: "I studied at the café — killed two birds with one stone." },
  { en: "Pull someone's leg", kr: "농담하다, 장난치다", ex: "Are you serious or just pulling my leg?" },
  { en: "Under the gun", kr: "압박을 받고 있다", ex: "We're under the gun to finish this project by Friday." },
  { en: "Bite the dust", kr: "실패하다, 쓰러지다", ex: "My old laptop finally bit the dust." },
  { en: "Get out of hand", kr: "통제 불능이 되다", ex: "The situation got completely out of hand." },
  { en: "Hit the sack", kr: "잠자리에 들다", ex: "I'm exhausted. I'm going to hit the sack." },
  { en: "Miss the boat", kr: "기회를 놓치다", ex: "You missed the boat on that scholarship deadline." },
  { en: "Cut corners", kr: "대충 하다, 지름길을 택하다", ex: "Don't cut corners on your thesis." },
  { en: "The tip of the iceberg", kr: "빙산의 일각", ex: "The problems we see are just the tip of the iceberg." },
  { en: "Go back to the drawing board", kr: "처음부터 다시 시작하다", ex: "The plan failed — let's go back to the drawing board." },
  { en: "Hit the ground running", kr: "처음부터 전속력으로 시작하다", ex: "We need to hit the ground running this semester." },
  { en: "In the same boat", kr: "같은 처지에 있다", ex: "We're all in the same boat with this deadline." },
  { en: "Let sleeping dogs lie", kr: "긁어 부스럼 만들지 마라", ex: "Just let sleeping dogs lie and move on." },
  { en: "No pain, no gain", kr: "고통 없이 얻는 것도 없다", ex: "Keep studying — no pain, no gain." },
  { en: "On the same page", kr: "같은 생각이다", ex: "Are we all on the same page about the deadline?" },
  { en: "Out of the blue", kr: "갑자기, 뜬금없이", ex: "He called me out of the blue after two years." },
  { en: "Pull an all-nighter", kr: "밤을 새우다", ex: "I had to pull an all-nighter before the exam." },
  { en: "Speak of the devil", kr: "호랑이도 제 말 하면 온다", ex: "Speak of the devil — here comes Minho now." },
  { en: "Take it with a grain of salt", kr: "액면 그대로 받아들이지 않다", ex: "Take his advice with a grain of salt." },
  { en: "The last straw", kr: "인내의 한계, 마지막 결정타", ex: "That failing grade was the last straw." },
  { en: "Up in the air", kr: "아직 불확실하다", ex: "My summer internship plans are still up in the air." },
  { en: "You can't judge a book by its cover", kr: "겉모습으로 판단하지 마라", ex: "He seemed cold at first — you can't judge a book by its cover." },
  { en: "Add fuel to the fire", kr: "불난 데 기름 붓다", ex: "His comment only added fuel to the fire." },
  { en: "At the drop of a hat", kr: "즉시, 망설임 없이", ex: "She's ready to help at the drop of a hat." },
  { en: "Back to square one", kr: "원점으로 돌아가다", ex: "The server crashed — back to square one." },
  { en: "Barking up the wrong tree", kr: "엉뚱한 데서 찾다", ex: "If you think I did it, you're barking up the wrong tree." },
  { en: "Bend over backwards", kr: "안간힘을 쓰다, 최선을 다하다", ex: "She bent over backwards to help us." },
  { en: "Blow off steam", kr: "스트레스를 풀다", ex: "I go to the gym to blow off steam after exams." },
  { en: "Burn bridges", kr: "돌이킬 수 없게 관계를 끊다", ex: "Don't burn bridges with your professors." },
  { en: "Call it a day", kr: "오늘은 이만 끝내다", ex: "We've done enough — let's call it a day." },
  { en: "Caught red-handed", kr: "현행범으로 잡히다", ex: "He was caught red-handed cheating on the test." },
  { en: "Come out of nowhere", kr: "갑자기 나타나다", ex: "That question on the exam came out of nowhere." },
  { en: "Cut to the chase", kr: "핵심으로 바로 가다", ex: "Let's cut to the chase — what's the actual problem?" },
  { en: "Down to earth", kr: "현실적인, 꾸밈없는", ex: "She's super down to earth despite her fame." },
  { en: "Every cloud has a silver lining", kr: "모든 불행에는 희망이 있다", ex: "Failing pushed me to study harder — every cloud has a silver lining." },
  { en: "Face the music", kr: "결과를 감수하다", ex: "You have to face the music and tell the professor." },
  { en: "Get cold feet", kr: "겁이 나서 포기하다", ex: "I got cold feet before the presentation." },
  { en: "Get the hang of it", kr: "요령을 터득하다", ex: "Calculus is hard at first, but you'll get the hang of it." },
  { en: "Give someone the benefit of the doubt", kr: "일단 믿어주다", ex: "Give him the benefit of the doubt — maybe he was just late." },
  { en: "Go the extra mile", kr: "한 발 더 나아가다", ex: "Going the extra mile on assignments really pays off." },
  { en: "Have a lot on one's plate", kr: "할 일이 너무 많다", ex: "I can't take more clubs — I already have a lot on my plate." },
  { en: "Hit it off", kr: "처음부터 잘 통하다", ex: "We hit it off immediately at orientation." },
  { en: "Jump on the bandwagon", kr: "유행을 따르다", ex: "Everyone jumped on the bandwagon with that app." },
  { en: "Keep one's fingers crossed", kr: "행운을 빌다", ex: "Keep your fingers crossed for my interview!" },
  { en: "Leave no stone unturned", kr: "모든 수단을 동원하다", ex: "Leave no stone unturned when preparing for the final." },
  { en: "Look on the bright side", kr: "긍정적으로 보다", ex: "Look on the bright side — at least you learned something." },
  { en: "Make ends meet", kr: "수입 안에서 생활하다", ex: "Part-time jobs help me make ends meet." },
  { en: "On thin ice", kr: "위태로운 상황에 있다", ex: "After missing three classes, I'm on thin ice." },
  { en: "Once bitten, twice shy", kr: "한 번 물리면 두 번은 조심한다", ex: "Once bitten, twice shy — I always back up my files now." },
  { en: "Sit on the fence", kr: "중립을 지키다, 결정을 못 내리다", ex: "You can't sit on the fence forever — decide already." },
  { en: "Skate on thin ice", kr: "위험한 상황을 자초하다", ex: "Submitting late again is skating on thin ice." },
  { en: "Sleep on it", kr: "하루 자고 생각해보다", ex: "Don't decide now — sleep on it." },
  { en: "Steal someone's thunder", kr: "남의 주목을 가로채다", ex: "He stole my thunder by announcing it first." },
  { en: "Take the bull by the horns", kr: "어려운 문제에 정면으로 맞서다", ex: "It's time to take the bull by the horns and talk to your advisor." },
  { en: "The best of both worlds", kr: "두 가지 모두 좋은 것", ex: "Working remotely gives me the best of both worlds." },
  { en: "Think outside the box", kr: "틀에서 벗어나 창의적으로 생각하다", ex: "We need to think outside the box for this project." },
  { en: "Through thick and thin", kr: "좋을 때나 나쁠 때나", ex: "True friends stick with you through thick and thin." },
  { en: "Throw in the towel", kr: "포기하다", ex: "Don't throw in the towel — the semester is almost over." },
  { en: "Twist someone's arm", kr: "억지로 설득하다", ex: "He had to twist my arm to join the study group." },
  { en: "Under someone's thumb", kr: "지배를 받다", ex: "I don't want to be under anyone's thumb." },
  { en: "Wrap one's head around", kr: "이해하다", ex: "I can't wrap my head around this differential equation." },
  { en: "Your guess is as good as mine", kr: "나도 모른다", ex: "When will grades come out? Your guess is as good as mine." },
  { en: "Ahead of the curve", kr: "시대를 앞서 가다", ex: "Starting your thesis early keeps you ahead of the curve." },
  { en: "All ears", kr: "귀 기울여 듣고 있다", ex: "Tell me what happened — I'm all ears." },
  { en: "Bite one's tongue", kr: "말을 참다", ex: "I had to bite my tongue during that lecture." },
  { en: "Bread and butter", kr: "주요 수입원, 기본", ex: "Linear algebra is the bread and butter of engineering." },
  { en: "By the skin of one's teeth", kr: "아슬아슬하게 겨우", ex: "I passed the exam by the skin of my teeth." },
  { en: "Come clean", kr: "솔직히 털어놓다", ex: "Just come clean and admit you didn't do the reading." },
  { en: "Don't cry over spilled milk", kr: "이미 엎질러진 물이다", ex: "The deadline passed — don't cry over spilled milk, prepare better next time." },
  { en: "Easier said than done", kr: "말이야 쉽지", ex: "Getting up at 6 AM is easier said than done." },
  { en: "Elbow grease", kr: "힘든 육체적 노력", ex: "All this assignment needs is a bit of elbow grease." },
  { en: "Feel under pressure", kr: "압박감을 느끼다", ex: "I constantly feel under pressure during finals week." },
  { en: "Get a taste of one's own medicine", kr: "자업자득을 당하다", ex: "He got a taste of his own medicine." },
  { en: "Get the ball rolling", kr: "일을 시작하다", ex: "Let's get the ball rolling on the group project." },
  { en: "Give it a shot", kr: "한번 해보다", ex: "I've never coded before, but I'll give it a shot." },
  { en: "Go back to basics", kr: "기본으로 돌아가다", ex: "When I'm stuck, I go back to basics." },
  { en: "Have the upper hand", kr: "우위에 있다", ex: "Students who prepared early have the upper hand." },
  { en: "In a nutshell", kr: "간단히 말하면", ex: "In a nutshell, we need more time to finish." },
  { en: "In over one's head", kr: "감당 못할 상황에 처하다", ex: "I signed up for too many things — I'm in over my head." },
  { en: "It takes two to tango", kr: "혼자 할 수 없다, 양쪽 다 책임이 있다", ex: "The argument wasn't one-sided — it takes two to tango." },
  { en: "Keep a low profile", kr: "눈에 띄지 않게 지내다", ex: "After the mistake, I'm keeping a low profile." },
  { en: "Leave someone in the dark", kr: "아무것도 알려주지 않다", ex: "Don't leave your teammates in the dark about your progress." },
  { en: "Like two peas in a pod", kr: "매우 닮은 두 사람", ex: "Those two are like two peas in a pod." },
  { en: "Make a long story short", kr: "간단히 말하면", ex: "To make a long story short, I failed the quiz." },
  { en: "Not beat around the bush", kr: "빙빙 돌리지 않다", ex: "I won't beat around the bush — your code has bugs." },
  { en: "On a roll", kr: "잘 풀리고 있다", ex: "I'm on a roll — finished three assignments today." },
  { en: "See eye to eye", kr: "의견이 일치하다", ex: "My lab partner and I don't always see eye to eye." },
  { en: "Take something at face value", kr: "액면 그대로 받아들이다", ex: "Don't take the syllabus at face value — read the fine print." },
];

// 오늘 날짜 기반으로 숙어 하나 선택 (하루 동안 동일)
export function getTodayIdiom() {
  const start = new Date(new Date().getFullYear(), 0, 0);
  const dayOfYear = Math.floor((Date.now() - start) / 864e5);
  return IDIOMS[dayOfYear % IDIOMS.length];
}

// 오늘 체크 여부
const DONE_KEY = () => `idiom_done_${new Date().toISOString().split('T')[0]}`;
export function isIdiomDoneToday() { return localStorage.getItem(DONE_KEY()) === '1'; }
export function markIdiomDone()    { localStorage.setItem(DONE_KEY(), '1'); }
